#!/usr/bin/env escript

%_______________________________________________________________
%
%    Args = init:get_arguments(),
%_______________________________________________________________
main(Args) ->
    updater_hw_devices:main(Args).



