#!/usr/bin/env escript

%_______________________________________________________________
%
%    Args = init:get_arguments(),
%_______________________________________________________________
main(Args) ->
    Background1 = lists:member("-g", Args),
    Background2 = lists:member("--background", Args),

    if
        (Background1 == true) or (Background2 == true) ->
            io:format("Running in background mode...~n"),
            spawn(updater_hw_devices, main, [Args]);

        true ->
            updater_hw_devices:main(Args)
    end.
    



